### ISSUE TITLE
distbin.com SSL certificate expired

### ISSUE THREAD

**Issue by emorrp1** [gobengo/distbin#12]
This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.

distbin.com uses an invalid security certificate.

The certificate expired on 24/06/18 10:21. The current time is 27/06/18 12:02.

**Comment by gobengo** [comment]
Thanks @emorrp1. I fixed it!
Here is a story of what happened. https://twitter.com/bengo/status/1012410306109165568
