### ISSUE TITLE
Distbin.com is down

### ISSUE THREAD

**Issue by N07070** [gobengo/distbin#37]
Hello,

Today I tried to visit the official distbin website, but it seems to be down, and the SSL cert seems to be expired. 

Is the project still active ?

Cheers

**Comment by filippodb** [comment]
is this project abandoned? 
The website is still down

**Comment by JOduMonT** [comment]
@filippodb last update 15month ago what do you think ?

**Comment by therealmaxmoon** [comment]
I discovered this project, because it would be a fediverse alternative to privatebin. But it looks like the main developer isn't even responding.

Does someone have a running instance?

**Comment by N07070** [comment]
Projet seems dead. So long !
